
# basic options
title: My Awesome Blog
author: Muhamad Febri Saputra
email: kim.febry11@gmail.com
description: My first blog
github_username:  muhamadfebri

# Build settings
markdown: kramdown
theme: minima
